### ISSUE TITLE
Kakboard fails on Wayland

### ISSUE THREAD

**Issue by gustavo-hms** [lePerdu/kakboard#11]
Hi! I'm on Ubuntu running Gnome inside a Wayland session, with `wl-clipboard` installed. Any attempt to copy to clipboard or paste from it fails. If, for instance, I try to copy something from Kakoune, the following message appears on the `*debug*` buffer:
```
shell stderr: <<<
Failed to connect to a Wayland server
>>>
```

On the other hand, if I run `wl-copy something` manually from a terminal, it just works.

Can it be, perhaps, a configuration issue?

Thanks in advance.

**Comment by lePerdu** [comment]
That's odd. What versions of Kakoune and `wl-clipboard` are you using? I can't reproduce this on Manjaro with SwayWM (Kakoune v2020.01.16, `wl-clipboard` 2.0.0). I'll try on GNOME at some point when I can.

Something you can try is messing with `XDG_RUNTIME_DIR` and `WAYLAND_DISPLAY`. The path `$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY` should be a socket that's created by GNOME. They should both be set already to something like `/run/user/<uid>` and `wayland-0`, but you can try specifying them explicitly for `wl-copy` and `wl-paste` (both inside and outside of Kakoune).

Inside Kakoune, try setting `kakboard_copy_cmd` and `kakboard_paste_cmd` and also just running the commands using Kakoune's `<a-|>` (pipe selections to a command) and `!` (insert command output) keys.

**Comment by gustavo-hms** [comment]
I used to use it on Manjaro's Sway  and I can confirm it works there. I can also confirm it works on Manjaro's Plasma Wayland. This is why I think the problem may be related to some configuration stuff. Specially because I suspect Gnome is messing up with my `XDG_DATA_DIRS`. But both `XDG_RUNTIME_DIR` and `WAYLAND_DISPLAY` point to the right place. It seems to be something else.

> What versions of Kakoune and wl-clipboard are you using?

Same versions as yours.

As I said, running `wl-copy something` or `echo something | wl-copy` works as expected. But piping a selection from within Kakoune to `wl-copy` using `<a-|> raises the same `Failed to connect` error.

I also noted that `nvim` works as expected and it uses the same `wl-clipboard` program.

> you can try specifying them explicitly for wl-copy and wl-paste

Do you mean by explicitly setting the environment variables?

**Comment by lePerdu** [comment]
Yes, I mean setting them explicitly for the invocation of the program like this:
`env XDG_RUNTIME_DIR=/var/run WAYLAND_DISPLAY=wayland-0 wl-copy`

**Comment by gustavo-hms** [comment]
That works. Thanks!

And I've just realised what was the source of the problem: I've installed Kakoune as a snap package, since the deb package provided by Ubuntu is a bit outdated. And the Gnome Desktop is breaking Snap configuation. It simply changes env variables at will. A bit selfish desktop I can say...
