### ISSUE TITLE
Automatically enabling kakboard

### ISSUE THREAD

**Issue by fn-ix** [lePerdu/kakboard#7]
Hello!

I'm having a problem with enabling kakboard on startup. When I add `kakboard-enable` to `kakrc`, I get the following error:
````
~/.config/kak/kakrc:2:1: 'kakboard-enable' 2:5: 'set-option' no window in context
/usr/share/kak/kakrc:28:1: 'evaluate-commands' 107:1: 'source' 2:1: 'kakboard-enable' 2:5: 'set-option' no window in context
error while parsing kakrc:
    1:1: 'source' 28:1: 'evaluate-commands' 107:1: 'source' 2:1: 'kakboard-enable' 2:5: 'set-option' no window in context
````
Setting the `declare-option -hidden bool kakboard_enabled` option from `false` to `true` in `kakboard.kak` makes no discernible difference either (if it's supposed to make any).

Note that I installed kakboard manually without the plugin manager.

**Comment by lePerdu** [comment]
`kakboard-enable` has to be run after a window has been created (which has not happened yet when the `kakrc` file is run). A good way to do this is to put it in a `WinCreate` hook like when using `plug.kak` (the last argument to the `plug` function is just code to run once the plugin is loaded):
```
hook global WinCreate .* %{ kakboard-enable }
```

`kakboard_enabled` is just just an internal flag to keep track of whether it's on for `kakboard-toggle` to work; it doesn't actually do anything by itself.

Sorry it's a bit unclear. I'll elaborate a bit in the manual installation section of the README.
