### ISSUE TITLE
kakboard_copy_keys not working as expected

### ISSUE THREAD

**Issue by gustavo-hms** [lePerdu/kakboard#9]
Hi! 

I don't like that Kakoune set `"` register when executing `d` and `c` keys. It's counter intuitive to me and, as such, quite annoying. It's a behaviour I don't understand Kakoune ported from vi. So, I have the following mappings:

```kak
map global normal <a-d> d
map global normal d <a-d>
map global normal c <a-c>
```

It's a personal preference, so it's OK if you don't like it.

If I have this plugin disabled, these mappings work well. But obviously they don't work with the plugin enabled. So, I tried to set `kakboard_copy_keys` like this:

```
set-option global kakboard_copy_keys <a-d> y
```

Pressing `y` works as expected, but nothing is copied to clipboard when pressing `<a-d>`. How can I make `<a-d>` copies to clipboard?

**Comment by lePerdu** [comment]
`kakboard_copy_keys` works by copying the contents of Kakoune's clipboard to the system clipboad after executing the key. Since `<a-d>` doesn't modify kakoune's clipboard, the last values copied will be sent to the system clipboard.

To get what you want, you will have to tell Kakboard to sync the clipboard in your own `<a-d>` mapping as such:
```
map global normal d <a-d>
map global normal c <a-c>
map global normal <a-d> ": kakboard-with-push-clipboard d<ret>"

set-option global kakboard_copy_keys y
# All this does is make the mapping:
# map global normal y ": kakboard-with-push-clipboard y<ret>"
```

**Comment by gustavo-hms** [comment]
That works. Thanks!

Just a last clarification:  by your explanation, I presume `kakboard_copy_keys` ignores mappings, otherwise `<a-d>` would in fact modify kakoune's clipboard, because it would be mapped to `d`. Is it right?

**Comment by lePerdu** [comment]
`kakboard-enable` creates mappings for all of the keys in `kakboard_copy_keys` which override your existing ones. It used to use hooks, which would work with existing mappings, but that had its own problems (I can't remember exactly what atm).

**Comment by gustavo-hms** [comment]
Hmm! This explains why it used to work...

Thank you!
